import { test,expect } from '@playwright/test';import { readFileSync } from 'node:fs';
const credentials=readFileSync('.runtime/demo-access.txt','utf8');const password=credentials.match(/Password: (.+)/)![1];
test('desktop storefront and customer pickup order',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1000});await page.goto('/');await expect(page.getByRole('heading',{name:'Fruity sips. Happy bites.'})).toBeVisible();await expect(page.getByRole('button',{name:'Add Fruity Soda',exact:true})).toBeVisible();await page.screenshot({path:'docs/screenshots/storefront-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Add Fruity Soda',exact:true}).click();await page.getByRole('button',{name:'16 oz'}).click();await page.getByRole('button',{name:'Green Apple',exact:true}).click();await page.getByRole('button',{name:/Add to basket/}).click();await page.getByLabel('Name for your order').fill('Browser pickup test');await page.getByRole('button',{name:'Place demo order'}).click();await expect(page.getByText('Happy bites ahead.')).toBeVisible();await page.getByRole('link',{name:'Track your order'}).click();await expect(page.getByRole('heading',{name:'Follow the flavor.'})).toBeVisible();expect(errors).toEqual([]);
});
test('mobile layouts at 320, 390, and 768 pixels stay within viewport',async({page})=>{
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.goto('/');await expect(page.getByRole('button',{name:'Add Fruity Soda',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/storefront-'+width+'.png',fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Add Fruity Soda',exact:true}).click();await page.getByRole('button',{name:'Strawberry',exact:true}).click();await page.getByRole('button',{name:/Add to basket/}).click();await expect(page.getByLabel('Name for your order')).toBeVisible();expect(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/mobile-cart.png'});
});
test('cashier sale and preparation flow',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/staff');await page.getByLabel('Username').fill('admin');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Open my workspace'}).click();await expect(page.getByRole('heading',{name:'Point of sale'})).toBeVisible();await page.screenshot({path:'docs/screenshots/pos-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Add Fruity Soda',exact:true}).click();await page.getByRole('button',{name:'Strawberry',exact:true}).click();await page.getByRole('button',{name:/Add to basket/}).click();
 const form=page.locator('.pos-cart');await form.getByLabel('Name for your order').fill('Browser cashier test');await form.getByLabel('Cash received (PHP)').fill('100');await form.getByRole('button',{name:'Complete sale'}).click();await expect(form.getByText('Happy bites ahead.')).toBeVisible();
 await page.getByRole('link',{name:'Preparation',exact:true}).click();const card=page.locator('.order-card').filter({hasText:'Browser cashier test'}).first();await card.getByRole('button',{name:'Start preparing'}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(card.getByRole('button',{name:'Mark ready'})).toBeVisible();
 await page.getByRole('link',{name:'Catalog & recipes'}).click();await expect(page.getByRole('heading',{name:'Catalog & recipes'})).toBeVisible();await page.getByRole('button',{name:'Create record'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
});
