import type { RequestHandler } from 'express';import { z } from 'zod';
import { createOrder,changeStatus,payOrder,refundOrder } from './services.js';import { readOrder } from './models.js';import { orderSchema,paymentSchema,transitionSchema } from './validators.js';import { db } from '../../database/connection.js';import { hash } from '../../shared/helpers/security.js';import { assert } from '../../shared/errors/app-error.js';
const idOf=(value:unknown)=>z.coerce.number().int().positive().parse(value);
export const placeOrder:RequestHandler=async(req,res)=>{const input=orderSchema.parse(req.body);const key=z.string().min(16).max(100).parse(req.get('Idempotency-Key'));if(!res.locals.staff)assert(!input.payment_method&&!input.tendered&&!input.reference,422,'Payment is collected by staff at pickup.');res.status(201).json(await createOrder(input,key,res.locals.staff));};
export const trackOrder:RequestHandler=async(req,res)=>{const value=z.string().regex(/^[a-f0-9]{64}$/).parse(req.params.token);const row=await db('orders').where({tracking_hash:hash(value)}).whereNull('deleted_at').first();assert(row,404,'Order not found.');const order=await readOrder(row.id);res.json({order_number:order.order_number,status:order.status,payment_status:order.payment_status,total_amount:order.total_amount,created_at:order.created_at,items:order.items.map((i:any)=>({product_name:i.product_name,serving:i.serving,quantity:i.quantity,options:i.options.map((o:any)=>({name:o.name,price:o.price})),unit_price:i.unit_price,line_total:i.line_total}))});};
export const listOrders:RequestHandler=async(req,res)=>{const limit=z.coerce.number().int().min(1).max(100).default(50).parse(req.query.limit);const q=db('orders').whereNull('deleted_at').orderBy('id','desc').limit(limit);if(req.query.active==='true')q.whereIn('status',['accepted','preparing','ready']);const rows=await q;res.json(await Promise.all(rows.map(r=>readOrder(r.id))));};
export const transition:RequestHandler=async(req,res)=>{const data=transitionSchema.parse(req.body);res.json(await changeStatus(idOf(req.params.id),data.status,data.reason,res.locals.staff));};
export const pay:RequestHandler=async(req,res)=>{res.json(await payOrder(idOf(req.params.id),paymentSchema.parse(req.body),res.locals.staff));};
export const refund:RequestHandler=async(req,res)=>{const data=z.object({amount:z.string(),reason:z.string().trim().min(1).max(500)}).parse(req.body);res.json(await refundOrder(idOf(req.params.id),data.amount,data.reason,res.locals.staff));};

