import { useEffect,useState } from 'react';import { Link,NavLink,Routes,Route } from 'react-router-dom';import { ShoppingBag,ChefHat,ClipboardList,Package,BarChart3,Settings as SettingsIcon,Users,LogOut,Store,Search } from 'lucide-react';
import type { Staff,Catalog,Product } from '../../../../contracts/types';import { api,setCsrf } from '../../shared/api';import { Brand } from '../../shared/components/brand';import { ProductCard } from '../storefront/storefront';import { ProductPicker } from '../../shared/components/product-picker';import { CartPanel } from '../../shared/components/cart-panel';import { Management,Inventory,Reports,Settings,StaffManagement } from '../admin/management';import { Orders } from './orders';import { useCart } from '../../shared/cart';
export function StaffArea(){
 const [staff,setStaff]=useState<Staff|null>(null),[loading,setLoading]=useState(true),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void api<{staff:Staff;csrf:string}>('/auth/session').then(v=>{setStaff(v.staff);setCsrf(v.csrf);}).catch(()=>{}).finally(()=>setLoading(false));},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const data=await api<{staff:Staff;csrf:string}>('/auth/login',{method:'POST',body:JSON.stringify({username,password})});setStaff(data.staff);setCsrf(data.csrf);setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{await api('/auth/logout',{method:'POST'});setStaff(null);setCsrf('');}catch(e){setError((e as Error).message);}}
 if(loading)return <div className="login-page"><p>Opening your workspace…</p></div>;
 if(!staff)return <div className="login-page gingham"><Link to="/" className="back-link">← Back to the storefront</Link><section className="login-card"><Brand/><p className="eyebrow">BEHIND EVERY HAPPY BITE</p><h1>Hello, team.</h1><p>Sign in to your Snacks Republic workspace.</p><form onSubmit={e=>void login(e)}><label>Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy?'Signing in…':'Open my workspace'}</button></form></section></div>;
 const manager=['admin','manager'].includes(staff.role),canSell=staff.role!=='kitchen';
 const links=[...(canSell?[{path:'',label:'Point of sale',icon:ShoppingBag}]:[]),{path:'preparation',label:'Preparation',icon:ChefHat},{path:'orders',label:'Orders',icon:ClipboardList},...(manager?[{path:'catalog',label:'Catalog & recipes',icon:Store},{path:'inventory',label:'Inventory',icon:Package},{path:'reports',label:'Sales overview',icon:BarChart3},{path:'settings',label:'Store settings',icon:SettingsIcon}]:[]),...(staff.role==='admin'?[{path:'team',label:'Team',icon:Users}]:[])];
 return <div className="staff-shell"><aside className="staff-sidebar"><Brand/><p className="sidebar-caption">YOUR WORKSPACE</p><nav aria-label="Staff navigation">{links.map(l=><NavLink key={l.path} to={'/staff'+(l.path?'/'+l.path:'')} end><l.icon size={19}/>{l.label}</NavLink>)}</nav><div className="staff-profile"><div className="avatar">{staff.name[0]}</div><span><strong>{staff.name}</strong><small>{staff.role}</small></span><button className="icon-button" onClick={()=>void logout()} aria-label="Sign out"><LogOut size={17}/></button></div></aside><div className="staff-main">{error&&<p className="error">{error}</p>}<Routes><Route index element={canSell?<Pos staff={staff}/>:<Orders staff={staff} queue/>}/><Route path="preparation" element={<Orders staff={staff} queue/>}/><Route path="orders" element={<Orders staff={staff}/>}/>{manager&&<><Route path="catalog" element={<Management/>}/><Route path="inventory" element={<Inventory/>}/><Route path="reports" element={<Reports/>}/><Route path="settings" element={<Settings/>}/></>}{staff.role==='admin'&&<Route path="team" element={<StaffManagement/>}/>}<Route path="*" element={<p>This workspace page is not available for your role.</p>}/></Routes></div></div>;
}
function Pos({staff}:{staff:Staff}){
 const [mobile,setMobile]=useState(()=>window.matchMedia('(max-width: 640px)').matches);
 useEffect(()=>{const media=window.matchMedia('(max-width: 640px)');const update=()=>setMobile(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const [catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(''),[q,setQ]=useState(''),[category,setCategory]=useState(0),[selected,setSelected]=useState<Product|null>(null);const cart=useCart();
 useEffect(()=>{void api<Catalog>('/catalog').then(setCatalog).catch(e=>setError(e.message));},[]);
 return <><div className="workspace-heading"><div><p className="eyebrow">LET'S MAKE SOMEONE'S DAY</p><h1>Point of sale</h1></div><span className="pill">{catalog?.demo?'Demo workspace':'In-store orders'}</span></div><div className="pos-layout"><section><label className="search-input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="Search POS products" placeholder="Search the menu…"/></label><div className="category-tabs pos-tabs"><button className={!category?'active':''} onClick={()=>setCategory(0)}>All</button>{catalog?.categories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div>{error&&<p className="error">{error}</p>}<div className="pos-products">{catalog?.products.filter(p=>(!category||p.category_id===category)&&p.name.toLowerCase().includes(q.toLowerCase())).map(p=><ProductCard key={p.id} product={p} compact onSelect={()=>setSelected(p)}/>)}</div>{!catalog&&!error&&<p>Loading menu…</p>}</section><CartPanel staff={staff} inline accepting={catalog?.store.accepting_orders} demo={catalog?.demo}/></div><button className="button mobile-pos-cart" onClick={()=>cart.setOpen(true)}><ShoppingBag size={18}/> Current order · {cart.count}</button>{mobile&&<CartPanel staff={staff} accepting={catalog?.store.accepting_orders} demo={catalog?.demo}/>}{selected&&<ProductPicker product={selected} onClose={()=>setSelected(null)} openCart={mobile}/>}</>;
}
