import type { Knex } from 'knex';
const stamps=(t:Knex.CreateTableBuilder,k:Knex)=>{t.dateTime('deleted_at',{precision:3}).nullable().index();t.dateTime('created_at',{precision:3}).notNullable().defaultTo(k.raw('CURRENT_TIMESTAMP(3)'));t.dateTime('updated_at',{precision:3}).notNullable().defaultTo(k.raw('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'));};
const fk=(t:Knex.CreateTableBuilder,name:string,table:string,nullable=false)=>{const c=t.integer(name).unsigned();if(nullable)c.nullable();else c.notNullable();c.references('id').inTable(table).onDelete('RESTRICT').index();return c;};
export const tables=['roles','staff','staff_sessions','categories','serving_options','products','product_variants','option_groups','options','product_option_groups','variant_options','units','ingredients','inventory_balances','recipe_items','option_recipe_items','customers','orders','order_items','order_item_options','payments','refunds','inventory_movements','order_status_history','idempotency_keys','store_settings','audit_logs'];
export async function up(k:Knex){
 const create=async(name:string,columns:(t:Knex.CreateTableBuilder)=>void)=>{await k.schema.createTable(name,t=>{t.increments('id');columns(t);stamps(t,k);});};
 await create('roles',t=>{t.string('code',30).notNullable().unique();t.string('name',80).notNullable();});
 await create('staff',t=>{fk(t,'role_id','roles');t.string('name',100).notNullable();t.string('username',80).notNullable().unique();t.string('password_hash',255).notNullable();});
 await create('staff_sessions',t=>{fk(t,'staff_id','staff');t.string('token_hash',64).notNullable().unique();t.string('csrf_token',64).notNullable();t.dateTime('expires_at',{precision:3}).notNullable().index();});
 await create('categories',t=>{t.string('name',80).notNullable();t.string('slug',100).notNullable().unique();});
 await create('serving_options',t=>{t.string('name',80).notNullable().unique();});
 await create('products',t=>{fk(t,'category_id','categories');t.string('name',150).notNullable();t.string('slug',180).notNullable().unique();t.text('description').notNullable();t.string('image_path',255).notNullable().defaultTo('/assets/soda-hero.png');t.boolean('is_published').notNullable().defaultTo(false);});
 await create('product_variants',t=>{fk(t,'product_id','products');fk(t,'serving_option_id','serving_options');t.string('sku',80).notNullable().unique();t.decimal('price',10,2).unsigned().nullable();t.boolean('recipe_ready').notNullable().defaultTo(false);t.unique(['product_id','serving_option_id']);});
 await create('option_groups',t=>{t.string('name',80).notNullable().unique();t.boolean('required').notNullable().defaultTo(false);t.integer('max_selections').unsigned().notNullable().defaultTo(1);});
 await create('options',t=>{fk(t,'option_group_id','option_groups');t.string('name',100).notNullable();t.unique(['option_group_id','name']);});
 await create('product_option_groups',t=>{fk(t,'product_id','products');fk(t,'option_group_id','option_groups');t.unique(['product_id','option_group_id']);});
 await create('variant_options',t=>{fk(t,'variant_id','product_variants');fk(t,'option_id','options');t.decimal('price',10,2).unsigned().notNullable().defaultTo(0);t.unique(['variant_id','option_id']);});
 await create('units',t=>{t.string('name',40).notNullable().unique();});
 await create('ingredients',t=>{fk(t,'unit_id','units');t.string('name',100).notNullable().unique();t.decimal('reorder_level',12,3).unsigned().notNullable().defaultTo(0);});
 await create('inventory_balances',t=>{fk(t,'ingredient_id','ingredients');t.unique(['ingredient_id']);t.decimal('quantity',12,3).unsigned().notNullable().defaultTo(0);});
 await create('recipe_items',t=>{fk(t,'variant_id','product_variants');fk(t,'ingredient_id','ingredients');t.decimal('quantity',12,3).unsigned().notNullable();t.unique(['variant_id','ingredient_id']);});
 await create('option_recipe_items',t=>{fk(t,'variant_option_id','variant_options');fk(t,'ingredient_id','ingredients');t.decimal('quantity',12,3).unsigned().notNullable();t.unique(['variant_option_id','ingredient_id']);});
 await create('customers',t=>{t.string('name',100).notNullable();t.string('phone',40).nullable();});
 await create('orders',t=>{t.string('order_number',40).notNullable().unique();t.enu('channel',['pos','online']).notNullable();fk(t,'staff_id','staff',true);fk(t,'customer_id','customers',true);t.string('customer_name',100).notNullable();t.enu('status',['accepted','preparing','ready','completed','cancelled']).notNullable().defaultTo('accepted').index();t.enu('payment_status',['unpaid','paid','partially_refunded','refunded']).notNullable().defaultTo('unpaid');t.string('currency',3).notNullable().defaultTo('PHP');t.decimal('subtotal',10,2).unsigned().notNullable();t.decimal('total_amount',10,2).unsigned().notNullable();t.string('notes',500).notNullable().defaultTo('');t.string('tracking_hash',64).notNullable().unique();t.string('tracking_nonce',64).notNullable();});
 await create('order_items',t=>{fk(t,'order_id','orders');fk(t,'variant_id','product_variants');t.string('product_name',150).notNullable();t.string('serving',80).notNullable();t.integer('quantity').unsigned().notNullable();t.decimal('unit_price',10,2).unsigned().notNullable();t.decimal('line_total',10,2).unsigned().notNullable();});
 await create('order_item_options',t=>{fk(t,'order_item_id','order_items');fk(t,'option_id','options');t.string('name',100).notNullable();t.decimal('price',10,2).unsigned().notNullable();});
 await create('payments',t=>{fk(t,'order_id','orders');t.unique(['order_id']);fk(t,'staff_id','staff');t.enu('method',['cash','gcash']).notNullable();t.decimal('amount',10,2).unsigned().notNullable();t.decimal('tendered',10,2).unsigned().notNullable();t.string('reference',100).nullable();});
 await create('refunds',t=>{fk(t,'payment_id','payments');fk(t,'staff_id','staff');t.decimal('amount',10,2).unsigned().notNullable();t.string('reason',500).notNullable();});
 await create('inventory_movements',t=>{fk(t,'ingredient_id','ingredients');fk(t,'order_item_id','order_items',true);fk(t,'staff_id','staff',true);fk(t,'reversal_id','inventory_movements',true);t.unique(['reversal_id']);t.decimal('quantity',12,3).notNullable();t.string('reason',255).notNullable();t.string('operation_key',100).notNullable().unique();});
 await create('order_status_history',t=>{fk(t,'order_id','orders');fk(t,'staff_id','staff',true);t.string('previous_status',30).nullable();t.string('new_status',30).notNullable();t.string('reason',500).nullable();});
 await create('idempotency_keys',t=>{t.string('scope',80).notNullable();t.string('request_key',100).notNullable();t.string('request_hash',64).notNullable();fk(t,'order_id','orders',true);t.unique(['scope','request_key']);});
 await create('store_settings',t=>{t.string('name',100).notNullable();t.string('headline',150).notNullable();t.text('about').notNullable();t.string('address',255).nullable();t.string('hours',255).nullable();t.string('phone',40).nullable();t.string('facebook_url',255).notNullable();t.string('currency',3).notNullable().defaultTo('PHP');t.boolean('accepting_orders').notNullable().defaultTo(false);});
 await create('audit_logs',t=>{fk(t,'staff_id','staff',true);t.string('action',80).notNullable();t.string('resource',80).notNullable();t.integer('resource_id').unsigned().nullable();t.text('summary').notNullable();});
}
export async function down(k:Knex){for(const name of [...tables].reverse())await k.schema.dropTable(name);}

