import { useMemo,useState } from 'react';import { Minus,Plus } from 'lucide-react';import type { Product } from '../../../../contracts/types';import { Dialog } from './dialog';import { peso } from '../api';import { useCart } from '../cart';
export function ProductPicker({product,onClose,openCart=true}:{product:Product;onClose:()=>void;openCart?:boolean}){
 const [variantId,setVariantId]=useState(product.variants.find(v=>v.price!==null)?.id||product.variants[0]?.id),[selected,setSelected]=useState<number[]>([]),[count,setCount]=useState(1),[error,setError]=useState('');
 const cart=useCart(),variant=product.variants.find(v=>v.id===variantId),options=product.options.filter(o=>o.variant_id===variantId);
 const groups=useMemo(()=>Array.from(new Map(options.map(o=>[o.group_id,{id:o.group_id,name:o.group_name,required:o.required}])).values()),[options]);
 const amount=Number(variant?.price||0)+options.filter(o=>selected.includes(o.id)).reduce((n,o)=>n+Number(o.price),0);
 function add(){if(!variant)return;const missing=groups.find(g=>g.required&&!options.some(o=>o.group_id===g.id&&selected.includes(o.id)));if(missing){setError('Please choose your '+missing.name.toLowerCase()+'.');return;}cart.add(product,variant,selected,count);onClose();if(openCart)cart.setOpen(true);}
 return <Dialog title={product.name} onClose={onClose}><div className="picker-description">{product.description}</div><fieldset><legend>Choose your serving</legend><div className="choice-grid">{product.variants.map(v=><button key={v.id} type="button" className={'choice '+(v.id===variantId?'selected':'')} aria-pressed={v.id===variantId} onClick={()=>{setVariantId(v.id);setSelected([]);}} disabled={v.price===null}><strong>{v.serving}</strong><span>{v.price===null?'Coming soon':peso(v.price)}</span></button>)}</div></fieldset>{groups.map(g=><fieldset key={g.id}><legend>{g.name} <small>{g.required?'Choose one':'Optional'}</small></legend><div className="choice-grid">{options.filter(o=>o.group_id===g.id).map(o=><button type="button" key={o.id} className={'choice '+(selected.includes(o.id)?'selected':'')} aria-pressed={selected.includes(o.id)} onClick={()=>{setError('');setSelected(old=>g.required?[...old.filter(id=>!options.some(x=>x.id===id&&x.group_id===g.id)),o.id]:old.includes(o.id)?old.filter(id=>id!==o.id):[...old,o.id]);}}><strong>{o.name}</strong>{Number(o.price)>0&&<span>+{peso(o.price)}</span>}</button>)}</div></fieldset>)}<div className="quantity-row"><span>Quantity</span><div className="stepper"><button aria-label="Decrease quantity" onClick={()=>setCount(n=>Math.max(1,n-1))}><Minus size={16}/></button><span>{count}</span><button aria-label="Increase quantity" onClick={()=>setCount(n=>Math.min(50,n+1))}><Plus size={16}/></button></div></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={!variant||variant.price===null||!variant.recipe_ready} onClick={add}>{variant?.recipe_ready?'Add to basket · '+peso(amount*count):'Not available for ordering yet'}</button></Dialog>;
}
