import { useEffect,useState } from 'react';import { Link } from 'react-router-dom';import { ArrowUpRight,ArrowDown,Search,ShoppingBag,Sparkles,Plus,Leaf,Heart,GlassWater,Utensils,ChevronRight } from 'lucide-react';
import type { Catalog,Product } from '../../../../contracts/types';import { api,peso } from '../../shared/api';import { Brand } from '../../shared/components/brand';import { useCart } from '../../shared/cart';import { CartPanel } from '../../shared/components/cart-panel';import { ProductPicker } from '../../shared/components/product-picker';
export function Storefront(){
 const [data,setData]=useState<Catalog|null>(null),[error,setError]=useState(''),[category,setCategory]=useState(0),[search,setSearch]=useState(''),[selected,setSelected]=useState<Product|null>(null);
 const [showAll,setShowAll]=useState(false);
 const cart=useCart();const load=()=>{setError('');void api<Catalog>('/catalog').then(setData).catch(e=>setError(e.message));};useEffect(load,[]);
 const products=data?.products.filter(p=>(!category||p.category_id===category)&&p.name.toLowerCase().includes(search.toLowerCase()))||[];
 const featured=[1,19,16,20];const displayed=!category&&!search&&!showAll?featured.map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p)):products;
 return <><div className="announcement">A LITTLE FIZZ. A LOT OF HAPPY. <span>✦</span> YOUR NEXT MERIENDA STARTS HERE.</div><header className="site-header"><Brand/><nav aria-label="Main navigation"><a href="#menu">Our menu</a><a href="#story">Our story</a><a href={data?.store.facebook_url||'https://www.facebook.com/profile.php?id=61591189150675'} target="_blank" rel="noreferrer">Say hello <ArrowUpRight size={14}/></a></nav><button className="basket-button" onClick={()=>cart.setOpen(true)}><ShoppingBag size={18}/><span>Basket</span><b>{cart.count}</b></button></header><main>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✦</span> YOUR DAILY DOSE OF DELIGHT</div><h1>Fruity sips.<br/><em>Happy bites.</em></h1><p>Big on flavor. Full of good vibes.<br/>Your favorite fruity sodas and comfort bites,<br className="desktop-only"/> all in one happy place.</p><a className="button" href="#menu">Find your happy <ArrowUpRight size={20}/></a><div className="hero-note"><span className="round-icon"><GlassWater size={17}/></span><span>Five fruity flavors.<br/><strong>One very happy you.</strong></span></div></div><div className="hero-art"><img className="hero-image" src="/assets/soda-hero.png" alt="Illustrative strawberry, green apple and lemonade sodas on a pink gingham table" fetchPriority="high" width="1536" height="1024"/><div className="hero-stamp"><Sparkles size={21}/><span>sip, snack<br/>& smile</span><small>THE REPUBLIC WAY</small></div><div className="hero-label"><span className="status-dot"/> MEET YOUR NEW HAPPY HOUR <ArrowDown size={14}/></div></div></section>
 <div className="flavor-ribbon" aria-label="Available soda flavors">{['Strawberry','Green Apple','Lychee','Blueberry','Fresh Lemonade'].map(f=><span key={f}>{f}<span aria-hidden="true">✦</span></span>)}</div>
 <section className="menu-section" id="menu"><div className="section-heading"><div><p className="eyebrow">A MENU MADE FOR YOUR MOOD</p><h2>What are you <em>craving?</em></h2></div><p>Something fizzy. Something filling.<br/>Always something to smile about.</p></div>{data?.demo&&<div className="demo-note"><Sparkles size={16}/><span>You're exploring our demo store. Orders and stock here are for trying things out.</span></div>}{data&&!data.store.accepting_orders&&<p className="notice">Online ordering is paused. You can still explore the menu.</p>}<div className="menu-toolbar"><div className="category-tabs" role="group" aria-label="Menu categories"><button className={!category?'active':''} onClick={()=>setCategory(0)}>All cravings</button>{data?.categories.filter(c=>c.id!==6).map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={category===c.id?'active':''}>{c.name}</button>)}</div><label className="search-input"><Search size={18}/><input aria-label="Search menu" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a favorite…"/></label></div>
 {error?<div className="empty"><h3>Our menu is taking a moment.</h3><p role="alert">{error}</p><button className="button secondary" onClick={load}>Try again</button></div>:!data?<div className="product-grid" aria-label="Loading menu" aria-busy="true">{[1,2,3,4].map(i=><div key={i} className="skeleton"/>)}</div>:products.length===0?<div className="empty"><Search size={32}/><h3>{search?'No matching cravings yet.':'More happy bites are on their way.'}</h3><p>{search?'Try another name or explore all categories.':'Check back for this part of our menu.'}</p><button className="text-button" onClick={()=>{setSearch('');setCategory(0);}}>See all favorites</button></div>:<div className="product-grid">{displayed.map(p=><ProductCard key={p.id} product={p} onSelect={()=>setSelected(p)}/>)}</div>}{data&&!category&&!search&&!showAll&&<div className="browse-more"><button className="button secondary" onClick={()=>setShowAll(true)}>Explore the full menu <ArrowUpRight size={17}/></button></div>}</section>
 <section className="story-section" id="story"><div className="story-art gingham"><img src="/assets/01-logo.png" alt="Snacks Republic by PJRB logo" loading="lazy"/><span className="story-seal">GOOD FOOD.<br/>GOOD MOOD.</span></div><div className="story-copy"><p className="eyebrow">A LITTLE ABOUT OUR REPUBLIC</p><h2>Your cravings.<br/><em>Our happy place.</em></h2><p>{data?.store.about||'Welcome to Snacks Republic by PJRB—your spot for refreshing fruity sodas and satisfying bites. From a quick merienda to a filling meal, find something for your craving.'}</p><div className="story-values"><span><GlassWater/> Fruity refreshment</span><span><Utensils/> Comfort favorites</span><span><Heart/> Happy moments</span></div><a className="text-button" href={data?.store.facebook_url||'https://www.facebook.com/profile.php?id=61591189150675'} target="_blank" rel="noreferrer">Get to know us on Facebook <ArrowUpRight size={18}/></a></div></section>
 <section className="closing-banner"><Leaf className="closing-leaf"/><p className="eyebrow">MAKE ROOM FOR SOMETHING HAPPY</p><h2>Your next favorite<br/>is just a sip away.</h2><a href="#menu" className="button yellow">Let's find it <ArrowUpRight size={18}/></a></section>
 </main><footer><Brand/><p>Fruity sips. Happy bites. Happy you.</p><div>{data?.store.address&&<p>{data.store.address}</p>}{data?.store.hours&&<p>{data.store.hours}</p>}{data?.store.phone&&<p>{data.store.phone}</p>}<Link to="/staff">Staff access <ChevronRight size={14}/></Link></div><small>© {new Date().getFullYear()} Snacks Republic by PJRB</small></footer>{cart.count>0&&<button className="mobile-basket button" onClick={()=>cart.setOpen(true)}><ShoppingBag size={18}/> View basket · {cart.count}<strong>{peso(cart.total)}</strong></button>}{selected&&<ProductPicker product={selected} onClose={()=>setSelected(null)}/>}<CartPanel accepting={data?.store.accepting_orders??false} demo={data?.demo}/></>;
}
export function ProductCard({product:p,onSelect,compact=false}:{product:Product;onSelect:()=>void;compact?:boolean}){
 const prices=p.variants.filter(v=>v.price!==null).map(v=>Number(v.price)),price=prices.length?Math.min(...prices):null;
 return <article className={'product-card '+(compact?'compact':'')}><button className={'product-image '+(p.category_id===1?'soda':p.image_path.match(/\/(noodles|spam-sandwich|hotdog-sandwich)\.png$/)?'clean':'poster')} onClick={onSelect} aria-label={'Choose '+p.name}><img src={p.image_path} alt={p.name} loading="lazy"/>{p.category_id===1&&<span className="product-badge"><Sparkles size={12}/> PICK YOUR FLAVOR</span>}</button><div className="product-info"><span className="product-category">{p.category}</span><h3>{p.name}</h3><span className="serving-label">{p.variants.length===1?p.variants[0].serving:'12, 16 & 22 oz'}</span>{!compact&&<p>{p.description}</p>}<div className="product-bottom"><span>{price===null?'Coming soon':<>{p.variants.length>1&&<small>from </small>}<strong>{peso(price)}</strong></>}</span><button onClick={onSelect} className="add-button" aria-label={'Add '+p.name} disabled={price===null}><Plus size={20}/></button></div></div></article>;
}
